[project]
name = "configs"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Viet Nguyen", email = "vietnhprivat@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.21,<0.10.0"]
build-backend = "uv_build"
